# Generated by Django 5.2.8 on 2025-12-19 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description appearing under the media')),
                ('media_type', models.CharField(choices=[('image', 'Farm Image (Upload)'), ('youtube', 'YouTube Video'), ('instagram', 'Instagram (Reel/Post)'), ('tiktok', 'TikTok Video')], default='image', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('social_url', models.URLField(blank=True, help_text='Paste the full YouTube, Instagram, or TikTok URL here', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.gallerycategory')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
