# Generated by Django 5.2.8 on 2025-12-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image for Farm Image type', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='social_url',
            field=models.URLField(blank=True, help_text='Paste full YouTube, Instagram, or TikTok URL', null=True),
        ),
    ]
