# Generated by Django 5.2.8 on 2025-12-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_galleryitem_image_alter_galleryitem_social_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name (for admin only)', max_length=200)),
                ('flyer_image', models.ImageField(help_text='The promotional flyer/banner image', upload_to='promotions/')),
                ('link_url', models.URLField(blank=True, help_text='Optional: Where to go when flyer is clicked (e.g., referral page or WhatsApp)', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Check to show popup site-wide')),
                ('show_once_per_session', models.BooleanField(default=True, help_text='If checked, popup shows only once per browser session')),
                ('delay_seconds', models.PositiveIntegerField(default=3, help_text='Seconds to wait before showing popup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Popup',
                'verbose_name_plural': 'Promotional Popups',
                'ordering': ['-created_at'],
            },
        ),
    ]
