# Generated by Django 5.2.8 on 2025-12-19 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_deliveryzone_order_preferred_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee in KES (0 = free delivery)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from checkout'),
        ),
    ]
