# Generated by Django 5.2.8 on 2025-12-23 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0002_productreview'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='cartitem_either_product_or_basket',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='merchandise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.merchandise'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'basket', 'merchandise')},
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('basket__isnull', True), ('merchandise__isnull', True), ('product__isnull', False)), models.Q(('basket__isnull', False), ('merchandise__isnull', True), ('product__isnull', True)), models.Q(('basket__isnull', True), ('merchandise__isnull', False), ('product__isnull', True)), _connector='OR'), name='cartitem_exactly_one_item_type'),
        ),
    ]
