# Generated by Django 5.2.8 on 2025-12-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Recipe Ingredient', 'verbose_name_plural': 'Recipe Ingredients'},
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='custom_name',
            field=models.CharField(blank=True, help_text="Fill this if ingredient is NOT a product in your shop (e.g. 'Salt', 'Olive oil', '2 cloves garlic')", max_length=200),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(help_text='e.g. 2 cups, 500g, 3 pieces, to taste', max_length=100),
        ),
    ]
